version: '3'

services:
  node:
    image: node:12-alpine
    user: node
    working_dir: /home/node/app
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    environment:
      HOST: 0.0.0.0
      PORT: 3030
    expose:
      - 3030
    volumes:
      - ./:/home/node/app
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host: ${DOMAIN}'
    networks:
      - web
    command: sh -c 'yarn && yarn build && yarn start'
    restart: ${RESTART}

networks:
  web:
    external: true
